server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-app
    username: postgres
    password: postgrespass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true

info:
  app:
    name: "Shop products"
    description: "level Spring2"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

